/**
 * Write a translator's stub for a new language.
 *
 *     npm run i18n:extract -- de Deutsch
 *
 * Produces `src/lib/i18n/locales/de.ts`: every chrome key and every content key
 * the game can draw, each with the English source as its value, in the order a
 * player meets them. A translator overwrites the values in place; nothing else
 * about the file has to change.
 *
 * Registering it is three lines in `src/lib/i18n/locales.ts` — deliberately by
 * hand, because a locale that appears in the picker the moment its file exists
 * is a locale a half-finished translation ships in. See `docs/design/i18n.md`.
 *
 * **Run through Vite rather than plain Node**, and there is no third-party
 * runner here: the catalogue and the content are ordinary TypeScript modules
 * with extensionless imports, which Node cannot resolve and Vite resolves
 * exactly as the app does. `vite` is already a devDependency; this costs
 * nothing and cannot drift from what the build sees.
 *
 * Never runs at build time. It writes a file into `src/`, which is the whole
 * point of it and the reason it is a tool rather than a plugin.
 */
import { mkdirSync, existsSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createServer } from 'vite'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')

const [code, ...endonymParts] = process.argv.slice(2)
const endonym = endonymParts.join(' ')

if (!code || !endonym) {
  console.error('usage: npm run i18n:extract -- <code> <endonym>')
  console.error('   eg: npm run i18n:extract -- de Deutsch')
  process.exit(1)
}

if (!/^[a-z]{2}(-[A-Za-z0-9]+)*$/.test(code)) {
  console.error(`"${code}" is not a language code. Expected something like "de" or "pt-BR".`)
  process.exit(1)
}

const out = join(ROOT, 'src', 'lib', 'i18n', 'locales', `${code}.ts`)
if (existsSync(out)) {
  // Overwriting would throw away work already done. Merging a stub into a
  // partial translation is a job for a diff, not for this.
  console.error(`${out} already exists. Delete it first if you mean to start over.`)
  process.exit(1)
}

const server = await createServer({
  root: ROOT,
  server: { middlewareMode: true },
  appType: 'custom',
  logLevel: 'warn',
})

try {
  const { EN } = await server.ssrLoadModule('/src/lib/i18n/en.ts')
  const { contentSources } = await server.ssrLoadModule('/src/lib/i18n/contentSources.ts')

  /** A TypeScript string literal, single-quoted, on one line. */
  const quote = (value) =>
    `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`

  const entries = (pairs) =>
    pairs.map(([key, english]) => `  ${quote(key)}: ${quote(english)},`).join('\n')

  const chrome = Object.entries(EN)
  const content = contentSources().map((s) => [s.key, s.english])

  const file = `import type { Messages } from '../en'
import type { ContentMessages } from '../content'
import type { LocaleDef } from '../locales'

/**
 * ${endonym} (\`${code}\`).
 *
 * Generated by \`npm run i18n:extract -- ${code} ${endonym}\` on ${new Date()
   .toISOString()
   .slice(0, 10)}. Every value below is the English source: translate in place.
 *
 * Anything left in English still *works* — the fallback is per key, so a
 * half-finished file is a half-translated game rather than a broken one. That
 * is also why registering this in \`locales.ts\` is a separate, deliberate step.
 *
 * Two rules a translator needs and nothing enforces for them:
 *
 * - **A \`{placeholder}\` must survive, spelled exactly.** Move it wherever the
 *   sentence needs it; do not translate the name inside the braces.
 * - **Some strings are budgeted.** \`docs/design/i18n.md\` lists the slots with a
 *   character limit and what happens past it. \`npm test\` checks them.
 */
export const MESSAGES: Partial<Messages> = {
${entries(chrome)}
}

/** Names and descriptions authored in \`content/\`. */
export const CONTENT: ContentMessages = {
${entries(content)}
}

export const ${code.replace(/[^a-z]/gi, '').toUpperCase()}: LocaleDef = {
  code: ${quote(code)},
  endonym: ${quote(endonym)},
  intl: ${quote(code)},
  messages: MESSAGES,
  content: CONTENT,
}
`

  mkdirSync(dirname(out), { recursive: true })
  writeFileSync(out, file, 'utf8')

  console.log(`Wrote ${out}`)
  console.log(`  ${chrome.length} chrome keys, ${content.length} content keys`)
  console.log(`Register it in src/lib/i18n/locales.ts when it is ready to ship.`)
} finally {
  await server.close()
}
